"""0010 add process module tables

Revision ID: 995d742c9332
Revises: 42cf5cee5714
Create Date: 2026-08-13 16:27:30.039908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995d742c9332'
down_revision: Union[str, Sequence[str], None] = '42cf5cee5714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_higher_better', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('simulation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=False),
    sa.Column('affected_indicator_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('baseline_run_id', sa.Uuid(), nullable=False),
    sa.Column('comparison_run_id', sa.Uuid(), nullable=False),
    sa.Column('diff_summary', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['comparison_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('simulated_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('absolute_change', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('percent_change', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rule_applied', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_table('scenario_comparisons')
    op.drop_table('simulation_runs')
    op.drop_table('scenario_inputs')
    op.drop_table('indicator_values')
    op.drop_table('scenarios')
    op.drop_table('simulation_rules')
    op.drop_table('indicators')
    # ### end Alembic commands ###